// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calcTrap_cpp
double calcTrap_cpp(NumericMatrix x);
RcppExport SEXP _fittr_calcTrap_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(calcTrap_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// empAUC_cpp
double empAUC_cpp(NumericMatrix xy);
RcppExport SEXP _fittr_empAUC_cpp(SEXP xySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy(xySEXP);
    rcpp_result_gen = Rcpp::wrap(empAUC_cpp(xy));
    return rcpp_result_gen;
END_RCPP
}
// roc_xy_cpp
NumericMatrix roc_xy_cpp(CharacterVector true_class, NumericVector predictions, String pos_class);
RcppExport SEXP _fittr_roc_xy_cpp(SEXP true_classSEXP, SEXP predictionsSEXP, SEXP pos_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type true_class(true_classSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type predictions(predictionsSEXP);
    Rcpp::traits::input_parameter< String >::type pos_class(pos_classSEXP);
    rcpp_result_gen = Rcpp::wrap(roc_xy_cpp(true_class, predictions, pos_class));
    return rcpp_result_gen;
END_RCPP
}
// roc_xy_cpp2
NumericMatrix roc_xy_cpp2(CharacterVector& true_class, NumericVector& predictions, String pos_class);
RcppExport SEXP _fittr_roc_xy_cpp2(SEXP true_classSEXP, SEXP predictionsSEXP, SEXP pos_classSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector& >::type true_class(true_classSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type predictions(predictionsSEXP);
    Rcpp::traits::input_parameter< String >::type pos_class(pos_classSEXP);
    rcpp_result_gen = Rcpp::wrap(roc_xy_cpp2(true_class, predictions, pos_class));
    return rcpp_result_gen;
END_RCPP
}
// eval_cut_cpp
NumericVector eval_cut_cpp(CharacterVector truth, NumericVector predicted, String pos_class, double cutoff);
RcppExport SEXP _fittr_eval_cut_cpp(SEXP truthSEXP, SEXP predictedSEXP, SEXP pos_classSEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type truth(truthSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type predicted(predictedSEXP);
    Rcpp::traits::input_parameter< String >::type pos_class(pos_classSEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_cut_cpp(truth, predicted, pos_class, cutoff));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fittr_calcTrap_cpp", (DL_FUNC) &_fittr_calcTrap_cpp, 1},
    {"_fittr_empAUC_cpp", (DL_FUNC) &_fittr_empAUC_cpp, 1},
    {"_fittr_roc_xy_cpp", (DL_FUNC) &_fittr_roc_xy_cpp, 3},
    {"_fittr_roc_xy_cpp2", (DL_FUNC) &_fittr_roc_xy_cpp2, 3},
    {"_fittr_eval_cut_cpp", (DL_FUNC) &_fittr_eval_cut_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_fittr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
